const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getData: () => ipcRenderer.invoke('data:get'),
  setData: (obj) => ipcRenderer.invoke('data:set', obj),
  openSetup: () => ipcRenderer.invoke('ui:openSetup'),
  openPopup: (date) => ipcRenderer.invoke('ui:openPopup', date),
  showWidget: () => ipcRenderer.invoke('widget:show'),
  hideWidget: () => ipcRenderer.invoke('widget:hide'),
  setWidgetBounds: (opts) => ipcRenderer.invoke('widget:setBounds', opts),
  snapCorner: (corner) => ipcRenderer.invoke('widget:snapCorner', corner),
  setInteractiveAreas: (areas) => ipcRenderer.invoke('widget:setInteractiveAreas', areas),
  setDragActive: (on) => ipcRenderer.invoke('widget:setDragActive', on),
  getWidgetBounds: () => ipcRenderer.invoke('widget:getBounds'),
  setAutostart: (on) => ipcRenderer.invoke('settings:autostart', on),
  setOpacity: (v) => ipcRenderer.invoke('settings:setOpacity', v),
  setSetupDirty: (on) => ipcRenderer.send('setup:setDirty', !!on),
  forceCloseSetup: () => ipcRenderer.send('setup:forceClose'),
  onAskClose: (cb) => { const h = () => cb(); ipcRenderer.on('setup:askClose', h); return () => ipcRenderer.removeListener('setup:askClose', h); },
  onDataChanged: (cb) => { const h = () => cb(); ipcRenderer.on('data:changed', h); return () => ipcRenderer.removeListener('data:changed', h); },
  testNotify: () => ipcRenderer.invoke('notify:test'),
  exportData: () => ipcRenderer.invoke('data:export'),
  importData: () => ipcRenderer.invoke('data:import'),
  logError: (msg) => ipcRenderer.send('log:error', msg),
  onBellRing: (cb) => { const h = (_e, kind) => cb(kind); ipcRenderer.on('bell:ring', h); return () => ipcRenderer.removeListener('bell:ring', h); },
  quit: () => ipcRenderer.invoke('app:quit')
});