plugins {
    id 'com.android.application'
}
android {
    namespace 'com.czwidget.mobile'
    compileSdk 34
    defaultConfig {
        applicationId "com.czwidget.mobile"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "0.2.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
